/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from './app.routing';
import * as import6 from '@angular/http';
import * as import7 from '@angular/forms';
import * as import8 from '@angular/platform-browser/animations';
import * as import9 from './app.service';
import * as import10 from './home/home.component.ngfactory';
import * as import11 from './auth/Login/login.component.ngfactory';
import * as import12 from './auth/Register/register.component.ngfactory';
import * as import13 from './bookmark/bookmark.component.ngfactory';
import * as import14 from './app.component.ngfactory';
import * as import15 from './home/home.component';
import * as import16 from './auth/Login/login.component';
import * as import17 from './auth/Register/register.component';
import * as import18 from './bookmark/bookmark.component';
import * as import19 from '@angular/animations/browser';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _ɵa_10:any;
  _UrlSerializer_11:import3.DefaultUrlSerializer;
  _RouterOutletMap_12:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_13:any;
  _LocationStrategy_14:any;
  _Location_15:import2.Location;
  _Compiler_16:import0.Compiler;
  _NgModuleFactoryLoader_17:import0.SystemJsNgModuleLoader;
  _ROUTES_18:any[];
  _Router_19:any;
  _RouterModule_20:import3.RouterModule;
  _AppRoutingModule_21:import5.AppRoutingModule;
  _HttpModule_22:import6.HttpModule;
  _ɵba_23:import7.ɵba;
  _FormsModule_24:import7.FormsModule;
  _ReactiveFormsModule_25:import7.ReactiveFormsModule;
  _BrowserAnimationsModule_26:import8.BrowserAnimationsModule;
  _AppModule_27:import1.AppModule;
  __LOCALE_ID_28:any;
  __NgLocalization_29:import2.NgLocaleLocalization;
  __APP_ID_30:any;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __DomSanitizer_33:import4.ɵe;
  __Sanitizer_34:any;
  __HAMMER_GESTURE_CONFIG_35:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_36:any[];
  __EventManager_37:import4.EventManager;
  __ɵDomSharedStylesHost_38:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_39:import4.ɵDomRendererFactory2;
  __AnimationDriver_40:any;
  __ɵAnimationStyleNormalizer_41:any;
  __ɵAnimationEngine_42:import8.ɵa;
  __RendererFactory2_43:any;
  __ɵSharedStylesHost_44:any;
  __Testability_45:import0.Testability;
  __Meta_46:import4.Meta;
  __Title_47:import4.Title;
  __ActivatedRoute_48:any;
  __NoPreloading_49:import3.NoPreloading;
  __PreloadingStrategy_50:any;
  __RouterPreloader_51:import3.RouterPreloader;
  __PreloadAllModules_52:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_53:any;
  __APP_BOOTSTRAP_LISTENER_54:any[];
  __BrowserXhr_55:import6.BrowserXhr;
  __ResponseOptions_56:import6.BaseResponseOptions;
  __XSRFStrategy_57:any;
  __XHRBackend_58:import6.XHRBackend;
  __RequestOptions_59:import6.BaseRequestOptions;
  __Http_60:any;
  __ɵi_61:import7.ɵi;
  __FormBuilder_62:import7.FormBuilder;
  __AppService_63:import9.AppService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import10.HomeComponentNgFactory,
      import11.LoginPageComponentNgFactory,
      import12.RegisterPageComponentNgFactory,
      import13.BookMarkComponentNgFactory,
      import14.AppComponentNgFactory
    ]
    ,[import14.AppComponentNgFactory]);
  }
  get _LOCALE_ID_28():any {
    if ((this.__LOCALE_ID_28 == null)) { (this.__LOCALE_ID_28 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_28;
  }
  get _NgLocalization_29():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_29 == null)) { (this.__NgLocalization_29 = new import2.NgLocaleLocalization(this._LOCALE_ID_28)); }
    return this.__NgLocalization_29;
  }
  get _APP_ID_30():any {
    if ((this.__APP_ID_30 == null)) { (this.__APP_ID_30 = import0.ɵg()); }
    return this.__APP_ID_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == null)) { (this.__IterableDiffers_31 = import0.ɵl()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == null)) { (this.__KeyValueDiffers_32 = import0.ɵm()); }
    return this.__KeyValueDiffers_32;
  }
  get _DomSanitizer_33():import4.ɵe {
    if ((this.__DomSanitizer_33 == null)) { (this.__DomSanitizer_33 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_33;
  }
  get _Sanitizer_34():any {
    if ((this.__Sanitizer_34 == null)) { (this.__Sanitizer_34 = this._DomSanitizer_33); }
    return this.__Sanitizer_34;
  }
  get _HAMMER_GESTURE_CONFIG_35():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_35 == null)) { (this.__HAMMER_GESTURE_CONFIG_35 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_35;
  }
  get _EVENT_MANAGER_PLUGINS_36():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_36 == null)) { (this.__EVENT_MANAGER_PLUGINS_36 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_35)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_36;
  }
  get _EventManager_37():import4.EventManager {
    if ((this.__EventManager_37 == null)) { (this.__EventManager_37 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_36,this.parent.get(import0.NgZone))); }
    return this.__EventManager_37;
  }
  get _ɵDomSharedStylesHost_38():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_38 == null)) { (this.__ɵDomSharedStylesHost_38 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_38;
  }
  get _ɵDomRendererFactory2_39():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_39 == null)) { (this.__ɵDomRendererFactory2_39 = new import4.ɵDomRendererFactory2(this._EventManager_37,this._ɵDomSharedStylesHost_38)); }
    return this.__ɵDomRendererFactory2_39;
  }
  get _AnimationDriver_40():any {
    if ((this.__AnimationDriver_40 == null)) { (this.__AnimationDriver_40 = import8.ɵb()); }
    return this.__AnimationDriver_40;
  }
  get _ɵAnimationStyleNormalizer_41():any {
    if ((this.__ɵAnimationStyleNormalizer_41 == null)) { (this.__ɵAnimationStyleNormalizer_41 = import8.ɵc()); }
    return this.__ɵAnimationStyleNormalizer_41;
  }
  get _ɵAnimationEngine_42():import8.ɵa {
    if ((this.__ɵAnimationEngine_42 == null)) { (this.__ɵAnimationEngine_42 = new import8.ɵa(this._AnimationDriver_40,this._ɵAnimationStyleNormalizer_41)); }
    return this.__ɵAnimationEngine_42;
  }
  get _RendererFactory2_43():any {
    if ((this.__RendererFactory2_43 == null)) { (this.__RendererFactory2_43 = import8.ɵd(this._ɵDomRendererFactory2_39,this._ɵAnimationEngine_42,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_43;
  }
  get _ɵSharedStylesHost_44():any {
    if ((this.__ɵSharedStylesHost_44 == null)) { (this.__ɵSharedStylesHost_44 = this._ɵDomSharedStylesHost_38); }
    return this.__ɵSharedStylesHost_44;
  }
  get _Testability_45():import0.Testability {
    if ((this.__Testability_45 == null)) { (this.__Testability_45 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_45;
  }
  get _Meta_46():import4.Meta {
    if ((this.__Meta_46 == null)) { (this.__Meta_46 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_46;
  }
  get _Title_47():import4.Title {
    if ((this.__Title_47 == null)) { (this.__Title_47 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_47;
  }
  get _ActivatedRoute_48():any {
    if ((this.__ActivatedRoute_48 == null)) { (this.__ActivatedRoute_48 = import3.ɵf(this._Router_19)); }
    return this.__ActivatedRoute_48;
  }
  get _NoPreloading_49():import3.NoPreloading {
    if ((this.__NoPreloading_49 == null)) { (this.__NoPreloading_49 = new import3.NoPreloading()); }
    return this.__NoPreloading_49;
  }
  get _PreloadingStrategy_50():any {
    if ((this.__PreloadingStrategy_50 == null)) { (this.__PreloadingStrategy_50 = this._NoPreloading_49); }
    return this.__PreloadingStrategy_50;
  }
  get _RouterPreloader_51():import3.RouterPreloader {
    if ((this.__RouterPreloader_51 == null)) { (this.__RouterPreloader_51 = new import3.RouterPreloader(this._Router_19,this._NgModuleFactoryLoader_17,this._Compiler_16,this,this._PreloadingStrategy_50)); }
    return this.__RouterPreloader_51;
  }
  get _PreloadAllModules_52():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_52 == null)) { (this.__PreloadAllModules_52 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_52;
  }
  get _ROUTER_INITIALIZER_53():any {
    if ((this.__ROUTER_INITIALIZER_53 == null)) { (this.__ROUTER_INITIALIZER_53 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_53;
  }
  get _APP_BOOTSTRAP_LISTENER_54():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_54 == null)) { (this.__APP_BOOTSTRAP_LISTENER_54 = [this._ROUTER_INITIALIZER_53]); }
    return this.__APP_BOOTSTRAP_LISTENER_54;
  }
  get _BrowserXhr_55():import6.BrowserXhr {
    if ((this.__BrowserXhr_55 == null)) { (this.__BrowserXhr_55 = new import6.BrowserXhr()); }
    return this.__BrowserXhr_55;
  }
  get _ResponseOptions_56():import6.BaseResponseOptions {
    if ((this.__ResponseOptions_56 == null)) { (this.__ResponseOptions_56 = new import6.BaseResponseOptions()); }
    return this.__ResponseOptions_56;
  }
  get _XSRFStrategy_57():any {
    if ((this.__XSRFStrategy_57 == null)) { (this.__XSRFStrategy_57 = import6.ɵb()); }
    return this.__XSRFStrategy_57;
  }
  get _XHRBackend_58():import6.XHRBackend {
    if ((this.__XHRBackend_58 == null)) { (this.__XHRBackend_58 = new import6.XHRBackend(this._BrowserXhr_55,this._ResponseOptions_56,this._XSRFStrategy_57)); }
    return this.__XHRBackend_58;
  }
  get _RequestOptions_59():import6.BaseRequestOptions {
    if ((this.__RequestOptions_59 == null)) { (this.__RequestOptions_59 = new import6.BaseRequestOptions()); }
    return this.__RequestOptions_59;
  }
  get _Http_60():any {
    if ((this.__Http_60 == null)) { (this.__Http_60 = import6.ɵc(this._XHRBackend_58,this._RequestOptions_59)); }
    return this.__Http_60;
  }
  get _ɵi_61():import7.ɵi {
    if ((this.__ɵi_61 == null)) { (this.__ɵi_61 = new import7.ɵi()); }
    return this.__ɵi_61;
  }
  get _FormBuilder_62():import7.FormBuilder {
    if ((this.__FormBuilder_62 == null)) { (this.__FormBuilder_62 = new import7.FormBuilder()); }
    return this.__FormBuilder_62;
  }
  get _AppService_63():import9.AppService {
    if ((this.__AppService_63 == null)) { (this.__AppService_63 = new import9.AppService(this._Http_60)); }
    return this.__AppService_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵa_10 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_11 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_12 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_13 = {};
    this._LocationStrategy_14 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_13);
    this._Location_15 = new import2.Location(this._LocationStrategy_14);
    this._Compiler_16 = new import0.Compiler();
    this._NgModuleFactoryLoader_17 = new import0.SystemJsNgModuleLoader(this._Compiler_16,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_18 = [[
        {
          path: '',
          component: import15.HomeComponent
        }
        ,
        {
          path: 'login',
          component: import16.LoginPageComponent
        }
        ,
        {
          path: 'register',
          component: import17.RegisterPageComponent
        }
        ,
        {
          path: 'bookmarks',
          component: import18.BookMarkComponent
        }

      ]
    ];
    this._Router_19 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_11,this._RouterOutletMap_12,this._Location_15,this,this._NgModuleFactoryLoader_17,this._Compiler_16,this._ROUTES_18,this._ROUTER_CONFIGURATION_13,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_20 = new import3.RouterModule(this._ɵa_10,this._Router_19);
    this._AppRoutingModule_21 = new import5.AppRoutingModule();
    this._HttpModule_22 = new import6.HttpModule();
    this._ɵba_23 = new import7.ɵba();
    this._FormsModule_24 = new import7.FormsModule();
    this._ReactiveFormsModule_25 = new import7.ReactiveFormsModule();
    this._BrowserAnimationsModule_26 = new import8.BrowserAnimationsModule();
    this._AppModule_27 = new import1.AppModule();
    return this._AppModule_27;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import3.ɵa)) { return this._ɵa_10; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_11; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_12; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_13; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_14; }
    if ((token === import2.Location)) { return this._Location_15; }
    if ((token === import0.Compiler)) { return this._Compiler_16; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_17; }
    if ((token === import3.ROUTES)) { return this._ROUTES_18; }
    if ((token === import3.Router)) { return this._Router_19; }
    if ((token === import3.RouterModule)) { return this._RouterModule_20; }
    if ((token === import5.AppRoutingModule)) { return this._AppRoutingModule_21; }
    if ((token === import6.HttpModule)) { return this._HttpModule_22; }
    if ((token === import7.ɵba)) { return this._ɵba_23; }
    if ((token === import7.FormsModule)) { return this._FormsModule_24; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_25; }
    if ((token === import8.BrowserAnimationsModule)) { return this._BrowserAnimationsModule_26; }
    if ((token === import1.AppModule)) { return this._AppModule_27; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_28; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_29; }
    if ((token === import0.APP_ID)) { return this._APP_ID_30; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_33; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_34; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_35; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_36; }
    if ((token === import4.EventManager)) { return this._EventManager_37; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_38; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_39; }
    if ((token === import19.AnimationDriver)) { return this._AnimationDriver_40; }
    if ((token === import19.ɵAnimationStyleNormalizer)) { return this._ɵAnimationStyleNormalizer_41; }
    if ((token === import19.ɵAnimationEngine)) { return this._ɵAnimationEngine_42; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_43; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_44; }
    if ((token === import0.Testability)) { return this._Testability_45; }
    if ((token === import4.Meta)) { return this._Meta_46; }
    if ((token === import4.Title)) { return this._Title_47; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_48; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_49; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_50; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_51; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_52; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_53; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_54; }
    if ((token === import6.BrowserXhr)) { return this._BrowserXhr_55; }
    if ((token === import6.ResponseOptions)) { return this._ResponseOptions_56; }
    if ((token === import6.XSRFStrategy)) { return this._XSRFStrategy_57; }
    if ((token === import6.XHRBackend)) { return this._XHRBackend_58; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_59; }
    if ((token === import6.Http)) { return this._Http_60; }
    if ((token === import7.ɵi)) { return this._ɵi_61; }
    if ((token === import7.FormBuilder)) { return this._FormBuilder_62; }
    if ((token === import9.AppService)) { return this._AppService_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_38 && this._ɵDomSharedStylesHost_38.ngOnDestroy());
    (this.__RouterPreloader_51 && this._RouterPreloader_51.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovZXhlcmNpc2Uvd2hhdGdvaW5ndG9uaWdodC9hc3NldHMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovZXhlcmNpc2Uvd2hhdGdvaW5ndG9uaWdodC9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
